version: "3"
services:
  icanhazallips:
    image: icanhazallips
    build:
      context: .
    networks:
      - mainnet
    restart: unless-stopped
    ports:
      - target: 8080
        publish: 9380
        mode: host
    entrypoint: ["/icanhazallips/icanhazallips"]
    cap_drop:
      - ALL
networks:
  mainnet:
    driver: bridge
