version: "3"
services:
  icanhazallips:
    image: icanhazallips
    build:
      context: .
    networks:
      - mainnet
    restart: unless-stopped
    ports:
      - "9380:8080"
    entrypoint: ["/icanhazallips/icanhazallips"]
    cap_drop:
      - ALL
networks:
  mainnet:
    driver: bridge
