version: "3"
services:
  icanhazallips:
    image: icanhazallips
    deploy:
      resources:
        limits:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    build:
      context: .
    networks:
      - haznet
    restart: unless-stopped
    entrypoint: ["/icanhazallips/icanhazallips"]
    cap_drop:
      - ALL
    environment:
      - APP_ADDR=:8080
      - APP_CONTEXT_TIMEOUT=10
      - APP_READ_HEADER_TIMEOUT=3
      - APP_READ_TIMEOUT=5
      - APP_WRITE_TIMEOUT=5
      - APP_IDLE_TIMEOUT=5
  nginx:
    image: haz_nginx
    deploy:
      resources:
        limits:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - "9380:443"
    networks:
      - haznet
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
networks:
  haznet:
    driver: bridge
